# Generated by Django 2.1.7 on 2019-04-13 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('active', models.BooleanField(default=1, verbose_name='Активность')),
                ('desc', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/category', verbose_name='Изображение')),
                ('sort', models.IntegerField(default=1, verbose_name='Сортировка')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
